#!/usr/bin/env ansible-playbook
---

- name: Demonstrate consuming a secret from Vault
  hosts: localhost
  gather_facts: no

  vars:
    vault_addr: "http://localhost:8200"
    vault_token: "token=hvs.OVWwDAoEvtdYh8Qe0nvFuOPE"

  tasks:
    - name: Show username and password
      ansible.builtin.debug:
        msg:
          - "username: {{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/my_secret:username') }}"
          - "password: {{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/my_secret:password') }}"
      environment:
        # These environment variables would normally come from Ansible Automation Platform.
        # See [here](https://docs.ansible.com/automation-controller/latest/html/userguide/credential_plugins.html#hashicorp-vault-secret-lookup).
        ANSIBLE_HASHI_VAULT_ADDR: "{{ vault_addr }}"
        ANSIBLE_HASHI_VAULT_TOKEN: "{{ vault_token }}"
