#!/usr/bin/env ansible-playbook
---

- name: Demonstrate consuming a secret from Vault
  hosts: localhost
  become: no
  gather_facts: no

  vars:
    vault_addr: "http://localhost:8200"
    vault_token: "token=hvs.OVWwDAoEvtdYh8Qe0nvFuOPE"

  tasks:
    - name: Show username
      ansible.builtin.debug:
        msg: "username: {{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/my_secret:username') }}"
      environment:
        ANSIBLE_HASHI_VAULT_ADDR: "{{ vault_addr }}"
        ANSIBLE_HASHI_VAULT_TOKEN: "{{ vault_token }}"
