---
version: "3.9"

services:
  vault:
    image: hashicorp/vault:latest
    #image: hashicorp/vault-enterprise:latest
    container_name: vault-success-package-demo
    cap_add:
      - IPC_LOCK
    command: server -dev
    volumes:
      - ./docker/vault/data:/vault/file
      - ./docker/vault/logs:/vault/logs
    #  - ./docker/vault/config:/vault/config
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://vault:8200
      VAULT_DEV_ROOT_TOKEN_ID: manual-root-token
      #VAULT_LICENSE: $VAULT_LICENSE
    ports:
      - 8200:8200
      - 8201:8201
    networks:
      vault:

networks:
  vault: